// Re-export all shared types from canonical sources.
// Import from here (../../types) inside feature modules.

export type {
  PriorityLevel,
  ReviewPeriod,
  Priority,
  RosieMemoryItem,
  RosieRecommendation,
  Commitment,
  Decision,
  TimelineEntry,
  Reflection,
  SecretRecord,
  PersonalData,
  NodeType,
  EdgeType,
  GraphNode,
  GraphEdge,
  KnowledgeGraphData,
  MissionPlan,
  MissionStep,
} from '../localData'

export type {
  VaultEnvelope,
  BackupPackage,
} from '../vault'

export type { RecoveryAuditEvent } from './recovery'

export type {
  CognitionDataCategory,
  CognitionFeatureSurface,
  CognitionConsentAction,
  CognitionConsentAuditEvent,
  CognitionConsent,
  UnderstandingContractState,
  UnderstandingProvenance,
  UnderstandingCorrection,
  UnderstandingReviewAction,
  UnderstandingReviewEvent,
  OperatorUnderstanding,
  CloudSyncConsentDeclaration,
  ConnectorPermissionLevel,
  ConnectorPermissionGrant,
  ConnectorConsentDeclaration,
  Phase3ConsentState,
  CognitiveSignalType,
  CognitiveSignalStatus,
  CognitiveSignalAuditAction,
  CognitiveSignalAuditEvent,
  CognitiveSignal,
  CognitiveSignalProvenance,
  DeterministicRule,
} from './cognitive'

export type {
  SummaryDetailMode,
  InformationDensity,
  EvidenceDepth,
  PlanningSequenceMode,
  ReviewTimingMode,
  ExpansionDefaults,
  AdaptationSettingKey,
  PresentationMappingConflictBehavior,
  PresentationMapping,
  ActiveAdaptation,
  PresentationOverride,
  PresentationValidationState,
  AdaptationExplanation,
  PresentationProfile,
  PresentationAdaptationAuditAction,
  PresentationAdaptationAuditEvent,
  SurfacePresentation,
} from './presentation'

export type {
  CapabilityId,
  AdapterId,
  CapabilityVersion,
  AdapterVersion,
  RegistryVersion,
  PolicyVersion,
  ConnectivityRequestPurpose,
  ConnectivityDataClassification,
  AllowedHttpMethod,
  AllowedProtocol,
  AllowedOrigin,
  AllowedPathPattern,
  TimeoutPolicy,
  RedirectPolicy,
  AuditAttribution,
  ConnectivityRule,
  CapabilityDeclaration,
  AdapterDeclaration,
  ConnectivityRequestDescriptor,
  PolicyRejectionReason,
  PolicyDecision,
  CancellationState,
  AdapterRegistrationResult,
  CapabilityRegistrationResult,
  RegistryValidationResult,
  ConnectivityRegistrySnapshot,
  ConnectivityAuditEventAction,
  ConnectivityAuditEvent,
} from './connectivity'

export type {
  DeviceIdentifier,
  DeviceDisplayLabel,
  DeviceKeyVersion,
  CryptoSuiteVersion,
  DeviceSchemaVersion,
  DevicePolicyVersion,
  DeviceStatus,
  DeviceTrustState,
  EnrollmentState,
  RevocationState,
  RevocationReason,
  OperatorApprovalRecord,
  DevicePublicIdentity,
  ReplacementRelationship,
  DeviceTrustRecord,
  IdentityLifecycleAuditAction,
  IdentityLifecycleAuditEvent,
  EnrollmentPackage,
  ProofChallenge,
  ProofOfPossession,
  DeviceMessagePurpose,
  SignedDeviceMessage,
  DeviceIdentityValidationResult,
  DeviceRegistryValidationResult,
  DeviceTrustRegistrySnapshot,
} from './deviceIdentity'
